### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by Shin-Kitahara** [valeoai/LightConvPoint#12]
Hello. 
I have a couple of questions for you all. In setup.py I get this error. 

---------------------------------------------------------------------------------------------------------------------------------------------------
Running command python setup.py egg_info
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "C:\Users\nicor\anaconda3\envs\FKAConv\LightConvPoint\setup.py", line 31, in <module>
      sys.argv.remove("--compile")
  ValueError: list.remove(x): x not in list
  ['C:\\Users\\nicor\\anaconda3\\envs\\FKAConv\\LightConvPoint\\setup.py', 'egg_info', '--egg-base', 'C:\\Users\\nicor\\AppData\\Local\\Temp\\pip-pip-egg-info-cmmwqvzq']
  LIGHTCONVPOINT -- COMPILING CPP MODULES
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: 'C:\Users\nicor\anaconda3\envs\FKAConv\python.exe' -c '
  exec(compile('"'"''"'"''"'"'
   This is <pip-setuptools-caller> -- a caller that pip uses to run setup.py
  
   - It imports setuptools before invoking setup.py, to enable projects that directly
     import from `distutils.core` to work with newer packaging standards.
   - It provides a clear error message when setuptools is not installed.
   - It sets `sys.argv[0]` to the underlying `setup.py`, when invoking `setup.py` so
     setuptools doesn'"'"'t think the script is `-c`. This avoids the following warning:
       manifest_maker: standard file '"'"'-c'"'"' not found".
   - It generates a shim setup.py, for handling setup.cfg-only projects.
  import os, sys, tokenize

  try:
      import setuptools
  except ImportError as error:
      print(
          "ERROR: Can not execute `setup.py` since setuptools is not available in "
          "the build environment.",
          file=sys.stderr,
      )
      sys.exit(1)

  __file__ = %r
  sys.argv[0] = __file__

  if os.path.exists(__file__):
      filename = __file__
      with tokenize.open(__file__) as f:
          setup_py_code = f.read()
  else:
      filename = "<auto-generated setuptools caller>"
      setup_py_code = "from setuptools import setup; setup()"

  exec(compile(setup_py_code, filename, "exec"))
  '"'"''"'"''"'"' % ('"'"'C:\\Users\\nicor\\anaconda3\\envs\\FKAConv\\LightConvPoint\\setup.py'"'"',), "<pip-setuptools-caller>", "exec"))' egg_info --egg-base 'C:\Users\nicor\AppData\Local\Temp\pip-pip-egg-info-cmmwqvzq'
  cwd: C:\Users\nicor\anaconda3\envs\FKAConv\LightConvPoint\
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
---------------------------------------------------------------------------------------------------------------------------------------------------
I would like to know how to resolve the error.
My environment is as follows:
Windows
cuda=10.1
torch=1.8.1
torchvison=0.9.1
pymongo=3.12.0
sacred=0.8.2

I would like to know in what environment you implemented it, including the version.
I apologies for my poor English.

**Comment by cama36** [comment]
Have you solved it？I guess it might be an issue with the environment version?
